version: '3.9'

name: "Readme Studio Docker Compose"
services:
  dev:
    container_name: readme-studio-container
    build:
      dockerfile: dev.Dockerfile
    working_dir: /readme-studio
    volumes:
      - type: bind
        source: .
        target: /readme-studio
    command: sleep infinity